global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 15m
  receiver: 'smtp'
receivers:
    - name: 'smtp'
      email_configs:
          - smarthost: smtp.gmail.com:587
            to: 'ALERT_RECIPIENT@gmail.com'
            from: 'SENDER@gmail.com'
            auth_username: 'SENDER@gmail.com'
            auth_password: "YOUR_GMAIL_APP_PASSWORD"
            send_resolved: true
            require_tls: true
